#define VIRTUAL_ADDRESS_BASE 0xC0000000
#define LINEAR_ADDRESS_BASE  0x00100000
#define KERNEL_LINK_ADDRESS  (KERNEL_BASE + EXT_MEM_SIZE)

#define P2V(x) (x + VIRTUAL_ADDRESS_BASE)
#define V2P(x) (x - VIRTUAL_ADDRESS_BASE)
